### ISSUE TITLE
Overlay doesn't hide and a second overlay appears over first one

### ISSUE THREAD

**Issue by tbl0605** [CarlosBonetti/jquery-loading#1]
Hello,
thank you for your nice plugin !
I don't know if it's a real issue (maybe I simply use incorrectly your plugin), but in some cases I get 2 overlays that never disappear.
It happens only when I modify html content (using html(strData)) *before* removing the overlay (using loading('stop')).

JQuery version is 1.11.1, tested on Chrome 35.

Example :

<form id='form-id' method="post" action="url_for_form_submit">
...
<input type="submit" id='submit-button-id'></input>
<div id='feedback-panel-id'></div>
</form>

Will work :
    $("#submit-button-id").click(function(event) {
        event.preventDefault();
        $("#feedback-panel-id").parent().hide();
        $("#feedback-panel-id").html('');
        $('body').loading({
            message: 'My overlay ...'
        });
        $.ajax({
            url: 'url_for_form_validation',
            type: "post",
            data: $("#form-id").serialize(),
            dataType: "html",
            success: function(strData) {
                if (strData !== '') {
                    // Put loading('stop') BEFORE html('').html(strData)
                    $('body').loading('stop');
                    $("#feedback-panel-id").html('').html(strData);
                    $("#feedback-panel-id").parent().show();
                } else {
                    $("#form-id").submit();
                }
            },
            error:function(){
                // Put loading('stop') BEFORE html('Error !')
                $('body').loading('stop');
                $("#feedback-panel-id").html('Error !');
                $("#feedback-panel-id").parent().show();
            }
        });
        return false;
    });

Will not work (the overlay doesn't hide and a second overlay appears over first one !) :
    $("#submit-button-id").click(function(event) {
        event.preventDefault();
        $("#feedback-panel-id").parent().hide();
        $("#feedback-panel-id").html('');
        $('body').loading({
            message: 'My message ...'
        });
        $.ajax({
            url: 'url_for_form_validation',
            type: "post",
            data: $("#form-id").serialize(),
            dataType: "html",
            success: function(strData) {
                if (strData !== '') {
                    $("#feedback-panel-id").html('').html(strData);
                    $("#feedback-panel-id").parent().show();
                    // Put loading('stop') AFTER html('').html(strData)
                    $('body').loading('stop');
                } else {
                    $("#form-id").submit();
                }
            },
            error:function(){
                $("#feedback-panel-id").html('Error !');
                $("#feedback-panel-id").parent().show();
                // Put loading('stop') AFTER html('Error !')
                $('body').loading('stop');
            }
        });
        return false;
    });

Thank you for your help :)

**Comment by CarlosBonetti** [comment]
I'm closing this since the error doesn't happen anymore
