### ISSUE TITLE
there is no destroy method

### ISSUE THREAD

**Issue by ziedmahdi** [CarlosBonetti/jquery-loading#13]
When I try to use the `destroy` method I get:

> jquery.loading.min.js:9 Uncaught TypeError: Cannot read property 'apply' of undefined
    at HTMLDivElement.<anonymous> (jquery.loading.min.js:9)
    at Function.each (jquery-1.11.1.min.js:2)
    at m.fn.init.each (jquery-1.11.1.min.js:2)
    at m.fn.init.a.fn.loading (jquery.loading.min.js:9)
    at <anonymous>:1:27

for reproduction, you can open the browser console on [the demo page](http://carlosbonetti.github.io/jquery-loading/) and type:
```js
    $('#loading-light-theme').loading('destroy')
```

**Comment by gopal-g** [comment]
True, I get the same error. This is required as every time we call loading on a single page the loading div gets added in the DOM instead of reloading the previously created.

**Comment by CarlosBonetti** [comment]
In fact the `destroy` method added with #10 was never released. Sorry for my mistake. The v1.3.0 was just released and should fix this.

**Comment by gopal-g** [comment]
Nice that makes it much better :) Thank you.
