### ISSUE TITLE
Does it possible to add a update message function?

### ISSUE THREAD

**Issue by KinkiWu** [CarlosBonetti/jquery-loading#14]
Which the update function can let user to update the loading object message?
for example:  
loading...
then update the mesasge to 
processing...
etc.

Thanks for your help.

**Comment by CarlosBonetti** [comment]
Hi @KinkiWu, if you want to change the message programatically, after the loading state has started, there's no easy way but you can do that:

```
$('.loading-overlay-content', $('#element').Loading().overlay).html('Processing...')
```

Maybe in the future we can provide a better way of doing that via a simple function call.

**Comment by CarlosBonetti** [comment]
In v1.3 it is also possible to call again the plugin, with no duplicated overlay.

Feel free to reopen this issue if you still have problems.

**Comment by KinkiWu** [comment]
Thanks CarlosBonetti, I just update the plugin to v1.3, it work normally. 
I am very appreciate your help.
