### ISSUE TITLE
critical dependency error on laravel mix

### ISSUE THREAD

**Issue by jarloyz** [CarlosBonetti/jquery-loading#17]
i got this error, can you explain me how to solve it?
thanks
WARNING in ./node_modules/jquery-easy-loading/dist/jquery.loading.min.js
9:147-174 Critical dependency: the request of a dependency is an expression
 @ ./node_modules/jquery-easy-loading/dist/jquery.loading.min.js
 @ ./resources/assets/js/app.js
 @ multi ./resources/assets/js/app.js ./resources/assets/sass/app.scss

**Comment by cmarfil** [comment]
same here @jarloyz u have fixed?
