### ISSUE TITLE
Issue using in a Bootstrap modal dialog

### ISSUE THREAD

**Issue by mikestu** [CarlosBonetti/jquery-loading#2]
I'm trying to use this to put a loading overlay on top of a Bootstrap dialog, but it does not have a high enough z-index to get above the Bootstrap modal.  I had to force it to use a higher number.  Is there any reason why you don't just always default it to be some gigantic z-index?  Also, the default Bootstrap styling makes the modal have rounded corners, but the overlay does not, so you can see the overlay over the corners.  Maybe the plugin could detect if the target has rounded corners, and if so, also round the overlay div.

My CSS:
.loading-overlay {
  display: table;
  opacity: 0.9;
  z-index: 25000 !important;
}

**Comment by CarlosBonetti** [comment]
The z-index is now set to the target z-index +1.

The rounded corners can be achieved by providing a custom overlay or a custom theme to the plugin.
