### ISSUE TITLE
Error: Cannot find module '[object Window]'

### ISSUE THREAD

**Issue by luigif** [CarlosBonetti/jquery-loading#20]
If module is required through Webpack (i.e. with require('jquery-easy-loading');) an error appears in the js console:

`Error: Cannot find module '[object Window]'`

This is due to the AMD define:

```
if (typeof define === 'function' && define.amd) {
      // AMD
      define(['jquery', window], factory);
}
```

that requires window.
I'm not sure if that is needed in some other situation, but changing the define to:

`define(['jquery'], factory);`

solves the issue in  my case.

**Comment by bawwtracs** [comment]
the same

**Comment by CarlosBonetti** [comment]
It should be fixed by upgrading to the latest `2.x` versions. Feel free to reopen this if the issue persists
