### ISSUE TITLE
loading('stop') displyaing the loading widget

### ISSUE THREAD

**Issue by Growiel** [CarlosBonetti/jquery-loading#7]
Hey guys,

When I use .loading('stop'); on an element that was NOT already displaying the widget, it starts displaying.

The expected behavior would be nothing. If i call loading('stop'); and there is no loading on this element, nothing should happen.

I know it's an on the edge case, but in my case sometimes it happens..

**Comment by CarlosBonetti** [comment]
Hi @Growiel ! You're right. Right now the first call with any parameter whatsoever will initiate the plugin. So first calls like `.loading('whatever')`, `.loading(5)` or `.loading(['test', 3, {}])` will all initiate the plugin, completely ignoring the arguments.

What could be done would be throwing an error like "Loading plugin object not initialized on this element" in case any parameter but a config object or `start` is given as argument. What do you think?

**Comment by Growiel** [comment]
Hi,

I still believe that nothing happening is the best behavior. When I call "stop", I expect it to stop. If there's nothing to stop because it wasn't started, then nothing happens.

A toggable error (debug: true ?) for the dev stage would be a sweet addition but I think throwing an error all the time is too harsh, sometimes due to timing (AJAX) purposes, my 'stop' will be called and my 'start' never will. I don't want my app to crash in those cases.

**Comment by CarlosBonetti** [comment]
Hi @Growiel. I just did an implementation about what we talked at a separate branch. I'm basically starting the plugin just if the calls are:
```js
$(...).loading('start');
$(...).loading('toggle');
$(...).loading();
$(...).loading({ ... })
```
Everything else will be ignored and won't start the plugin. I also did some unit tests. Can you take a look before I merge it to master?

**Comment by Growiel** [comment]
Hi, sorry for the long delay.

I tested it and it seems to be doing what we would expect.

Thanks for the quick fix!

**Comment by CarlosBonetti** [comment]
Thanks for the help!
