### ISSUE TITLE
Nuget package deployment

### ISSUE THREAD

**Issue by daredev** [CarlosBonetti/jquery-loading#9]
I'd love to be able to install the package through Visual Studio's Nuget Package Manager. Creating and deploying is very easy, here you can find the details: [https://docs.nuget.org/Create/using-a-gui-to-build-packages](https://docs.nuget.org/Create/using-a-gui-to-build-packages)

**Comment by CarlosBonetti** [comment]
Don't feel it like really necessary, unless more people really want it.

Suggest you to go with the default `npm` for now or use a CDN like jsdelivr: https://www.jsdelivr.com/package/npm/jquery-easy-loading
